<?xml version="1.0" encoding="utf-8"?>

<!--
  Copyright (c) 1999-2004 DataPower Technology, Inc.
  All Rights Reserved.
-->
<!--
  Licensed Materials - Property of IBM
  IBM WebSphere DataPower Appliances
  Copyright IBM Corporation 2007. All Rights Reserved.
  US Government Users Restricted Rights - Use, duplication or disclosure
  restricted by GSA ADP Schedule Contract with IBM Corp.
-->

<definitions name="xml-mgmt"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:wsdlsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
  xmlns:wsdltns="http://www.datapower.com/schemas/management/wsdl"
  xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/"
  xmlns:tns="http://www.datapower.com/schemas/management"
  targetNamespace="http://www.datapower.com/schemas/management/wsdl">

  <types>
    <xsd:schema
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://www.datapower.com/schemas/management"
        targetNamespace="http://www.datapower.com/schemas/management">
      <xsd:include schemaLocation="xml-mgmt-ops.xsd"/>
    </xsd:schema>
  </types>

  <message name="request">
    <part name="body" element="tns:request"/>
  </message>

  <message name="response">
    <part name="body" element="tns:response"/>
  </message>

  <portType name="xml-mgmt">
    <operation name="operation">
      <input message="wsdltns:request"/>
      <output message="wsdltns:response"/>
    </operation>
  </portType>

  <binding name="xml-mgmt-soap" type="wsdltns:xml-mgmt">
    <wsdlsoap:binding style="document"
      transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="operation">
      <wsdlsoap:operation soapAction="" style="document"/>
      <input>
        <wsdlsoap:body use="literal"/>
      </input>
      <output>
        <wsdlsoap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="xml-mgmt">
    <port name="xml-mgmt" binding="wsdltns:xml-mgmt-soap">
      <documentation>
        <wsi:Claim conformsTo="http://ws-i.org/profiles/basic/1.0"></wsi:Claim>
      </documentation>
      <wsdlsoap:address location="https://*host:port*/service/mgmt/3.0"/>
    </port>
  </service>

  <!-- SOAP 1.2 bindings are generated by xmlmgmt-produce-wsdl.xsl -->
</definitions>
